# -*- coding: utf-8 -*-
"""HW_Python_Flow_Control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdjIjugAJNma5BiCfCaYVFfKbaRVmNeU
"""

#Python Flow Control Assignment
# %% [code]
# Write all code needed in this cell:

sex = input("Patient sex: ")
height = float(input("Patient height: "))
weight = float(input("Patient weight: "))

###################################

too_tall_flag = False
too_short_flag = False
too_heavy_flag = False
too_light_flag = False

# Do not change anything above this line!
# Start writing your code below:
if sex:
  first_letter = sex[0].lower()
  if first_letter == "m" or first_letter == "1":
    sex = "Male"
    print("Male")
  elif first_letter == "f" or first_letter == "w" or first_letter == "0":
    sex = "Female"
    print("Female")
  else:
    print(f"Invalid sex input: {sex}.Please enter sex.")
if sex == "Male":
  if height < 62:
    too_short_flag = True
    print("Patient is too short.")
  elif height > 80:
    too_tall_flag = True
    print("Patient is too tall.")
  else:
    print("Patient is correct height.")
elif sex == "Female":
  if height < 59:
    too_short_flag = True
    print("Patient is too short.")
  elif height > 71:
      too_tall_flag = True
      print("Patient is too tall.")
  else:
    print("Patient is correct height.")
if sex == "Male":
  if weight < 150:
    too_light_flag = True
    print("Patient is too light.")
  elif weight > 280:
    too_heavy_flag = True
    print("Patient is too heavy.")
  else:
    print("Patient is correct weight.")
elif sex == "Female":
  if weight < 100:
    too_light_flag = True
    print("Patient is too light.")
  elif weight > 180:
    too_heavy_flag = True
    print("Patient is too heavy.")
  else:
    print("Patient is correct weight.")

# Python IPO Assignment
# %% [code]
# Write all code needed in this cell:

employee1 = input("What is the first employees name?")
employee2 = input("What is the second employees name?")
employee3 = input("What is the third employees name?")
w1 = int(input("How many hours did "+ employee1 + " work?"))
w2 = int(input("How many hours did "+ employee2 + " work?"))
w3 = int(input("How many hours did "+ employee3 + " work?"))
hourly_rate_1 = float(input("How much does "+ employee1 + " make an hour?"))
hourly_rate_2 = float(input("How much does "+ employee2 + " make an hour?"))
hourly_rate_3 = float(input("How much does "+ employee3 + " make an hour?"))


###################################

tax_rate = .2

employee1_gross_pay = 0
employee2_gross_pay = 0
employee3_gross_pay = 0

employee1_taxes_owed = 0
employee2_taxes_owed = 0
employee3_taxes_owed = 0

employee1_net_pay = 0
employee2_net_pay = 0
employee3_net_pay = 0

# Use these variables below by changing their values.
# Do not change anything above this line!!!

#Process
#Gross Pay Calculation
if w1<=40:
  employee1_gross_pay = w1 * hourly_rate_1
  if w1>40:
    employee1_gross_pay = (hourly_rate_1 * 1.5)
  elif w1>50:
    employee1_gross_pay = (hourly_rate_1 * 1.6)
if w2<=40:
  employee2_gross_pay = w2 * hourly_rate_2
  if w2>40:
    employee2_gross_pay = (hourly_rate_2 * 1.5)
  elif w2>50:
    employee2_gross_pay = (hourly_rate_2 * 1.6)
if w3<=40:
  employee3_gross_pay = w3 * hourly_rate_3
  if w3>40:
    employee3_gross_pay = (hourly_rate_3 * 1.5)
  elif w3>50:
    employee3_gross_pay = (hourly_rate_3 * 1.6)

#Net Pay Calculation
if w1<=40:
  employee1_net_pay = w1 * hourly_rate_1 * (1-tax_rate)
  if w1>40:
    employee1_net_pay = (hourly_rate_1 * 1.5) * (1-tax_rate)
  elif w1>50:
    employee1_net_pay = (hourly_rate_1 * 1.6)* (1-tax_rate)
if w2<=40:
  employee2_net_pay = w2 * hourly_rate_2 * (1-tax_rate)
  if w2>40:
    employee2_net_pay = (hourly_rate_2 * 1.5) * (1-tax_rate)
  elif w2>50:
    employee2_net_pay = (hourly_rate_2 * 1.6)* (1-tax_rate)
if w3<=40:
  employee3_net_pay = w3 * hourly_rate_3 * (1-tax_rate)
  if w3>40:
    employee3_net_pay = (hourly_rate_3 * 1.5) * (1-tax_rate)
  elif w3>50:
    employee3_net_pay = (hourly_rate_3 * 1.6)* (1-tax_rate)
total_w = w1+w2+w3
total_hourly_wage = hourly_rate_1+hourly_rate_2+hourly_rate_3
total_gross_pay = employee1_gross_pay+employee2_gross_pay+employee3_gross_pay
total_net_pay = employee1_net_pay+employee2_net_pay+employee3_net_pay
employee_count = 3

#Output
print("\033[4mEmployee Name  Hours Worked  Hourly Wage  Tax Rate  Gross Pay  Net Pay\033[0;37;48m")
print(f'\033[1m {employee1:^15} \033[0m{w1:^7} {hourly_rate_1:^20.2f} {tax_rate:^0.2f} {employee1_gross_pay:^9.2f} \033[91m{employee1_net_pay:^10.2f}\033[37m')
print(f'\033[1m {employee2:^15} \033[0m{w2:^7} {hourly_rate_2:^20.2f} {tax_rate:^0.2f} {employee2_gross_pay:^9.2f} \033[91m{employee2_net_pay:^10.2f}\033[37m')
print(f'\033[4m\033[1m {employee3:^15} \033[0m\033[4m{w3:^7} {hourly_rate_3:^20.2f} {tax_rate:^0.2f} {employee3_gross_pay:^9.2f} \033[91m{employee3_net_pay:^10.2f}\033[37m\033[0m')
print(f'\033[1m {employee_count:^15} \033[0m{total_w:^7} {total_hourly_wage:^20.2f} {tax_rate:^0.2f} {total_gross_pay:^9.2f} \033[91m{total_net_pay:^10.2f}')